### ISSUE TITLE
Don't create a note for if an event has no guests

### ISSUE THREAD

**Issue by mkalela** [daubejb/meeting-notes-for-google-calendar#1]
Would it be possible to tweak this great script so that it wouldn't create a note for an event if there are no guests for it? This way I wouldn't end up having blank note docs for events I have created just for myself in my calendar.

**Comment by daubejb** [comment]
mkalela

Good suggestion.  I have amended the script to not create a file if the meeting contains no invitees.  Thank you

Jeff
